services:
  server:
    container_name: ci-wallet-bot
    build:
      context: ..
    environment:
      TELEGRAM_API_TOKEN: ${TELEGRAM_API_TOKEN}
      TELEGRAM_MINIAPP_URL: ${TELEGRAM_MINIAPP_URL}
      KAFKA_1_HOST: ${KAFKA_1_HOST}
      KAFKA_1_PORT: ${KAFKA_1_PORT}
    ports:
        - 9992:9992

  