


name: Deploy

on:
  push:
    branches:
      - main

jobs:
  docker-compose:
    runs-on: self-hosted
    environment: docker
    steps:
    - name: Checkout code
      uses: actions/checkout@v2 

    - name: Run Docker compose command
      env:
        TELEGRAM_API_TOKEN: ${{ secrets.TELEGRAM_API_TOKEN }}
        TELEGRAM_MINIAPP_URL: ${{ secrets.TELEGRAM_MINIAPP_URL }}
      
      run: docker compose -f docker/production.yaml -p ci-wallet-bot up --build -d --force-recreate

#docker compose -f .docker/development.yaml -p ci-wallet-bot up --build -d --force-recreate
 
